config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bsc-wdc/compss:
      branch: stable
      repo: https://github.com/bsc-wdc/compss
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-flax-angelfish.sh
        container: qc.acc_scanty-malachite-corgi
  QC.Doc:
    repos:
      github.com/bsc-wdc/compss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-olivine-worm.sh
        container: qc.doc_droopy-periwinkle-wallaby
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-corn-shrimp.sh
        container: qc.doc_geeky-lilac-affenpinscher
      github.com/bsc-wdc/compss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-wheat-horse.sh
        container: qc.doc_muggy-lemon-dog
      github.com/bsc-wdc/compss restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-gamboge-sparrow.sh
        container: qc.doc_leaky-scarlet-bandicoot
  QC.Lic:
    repos:
      github.com/bsc-wdc/compss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-asparagus-foxhound.sh
        container: qc.lic_cranky-chestnut-audemer
  QC.Sec:
    repos:
      github.com/bsc-wdc/compss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-sangria-dane.sh
        container: qc.sec_wiggy-black-scorpion
  QC.Sty:
    repos:
      github.com/bsc-wdc/compss checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-jade-ant.sh
        container: qc.sty_surly-beige-tang
      github.com/bsc-wdc/compss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-charcoal-mandrill.sh
        container: qc.sty_homely-bronze-wolf
      github.com/bsc-wdc/compss hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-silver-ladybird.sh
        container: qc.sty_snazzy-turquoise-salamander
      github.com/bsc-wdc/compss jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-vermilion-beetle.sh
        container: qc.sty_leaky-emerald-lobster
  QC.Ver:
    repos:
      github.com/bsc-wdc/compss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-grey-snake.sh
        container: qc.ver_goopy-myrtle-skunk
timeout: 1800
