config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bsc-wdc/compss:
      branch: stable
      repo: https://github.com/bsc-wdc/compss
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-teal-panda.sh
        container: qc.acc_flimsy-lilac-oriole
  QC.Doc:
    repos:
      github.com/bsc-wdc/compss find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-buff-bison.sh
        container: qc.doc_squeaky-purple-capybara
      github.com/bsc-wdc/compss git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-ivory-crane.sh
        container: qc.doc_whiny-puce-eel
      github.com/bsc-wdc/compss markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-purple-hamster.sh
        container: qc.doc_cranky-tomato-worm
      github.com/bsc-wdc/compss restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-olive-gibbon.sh
        container: qc.doc_hasty-chocolate-leopard
  QC.Lic:
    repos:
      github.com/bsc-wdc/compss licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-bronze-kiwi.sh
        container: qc.lic_lumpy-taupe-heron
  QC.Sec:
    repos:
      github.com/bsc-wdc/compss bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-rose-tamarin.sh
        container: qc.sec_chewy-bistre-mammoth
  QC.Sty:
    repos:
      github.com/bsc-wdc/compss checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-red-harrier.sh
        container: qc.sty_cheeky-mauve-walrus
      github.com/bsc-wdc/compss flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-teal-dane.sh
        container: qc.sty_muzzy-ultramarine-buffalo
      github.com/bsc-wdc/compss hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-aqua-earwig.sh
        container: qc.sty_cheeky-turquoise-bee
      github.com/bsc-wdc/compss jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-sepia-swan.sh
        container: qc.sty_ready-orange-turkey
  QC.Ver:
    repos:
      github.com/bsc-wdc/compss get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-brown-eagle.sh
        container: qc.ver_wiggy-sapphire-sponge
timeout: 5400
